### PR TITLE
Test gg marginal under ggplot2 v3.2.0

### PR DESCRIPTION
**Pull request by crew102**
Adds expected test figs under ggplot2 version 3.2.0 and updates expected test figs under dev version of ggplot2

### CODE REVIEW

**Comment by crew102** [comment]
More issues with installing dev version of ggplot2. I'll take a look later this week and update this PR then.

**Comment by crew102** [comment]
This was failing b/c we were hitting Github's API throttling limits (issue related to #140). I'm not sure why we were hitting these limits, though, as we both have the GITHUB_PAT envvar set in Travis. This means that we should have been successfully authenticating to the API, and hence not been subject to the relatively low rate limits placed on non-authenticated requests. Anyway, I created a new access token by following the steps in https://github.com/r-lib/remotes/issues/210#issuecomment-448582301 and that seemed to fix the build. Can you create a new token, store it as GITHUB_PAT in Travis, and restart the build?

**Comment by daattali** [comment]
Done. Restarting the build

**Comment by crew102** [comment]
Forgot to mention, this PR closes #141

**Pull request merged**
