### PR TITLE
Refactor ggextra

### PR DESCRIPTION
**Pull request by crew102**
This PR does some minor refactoring of ggExtra. Highlights include using positional params instead of keyword params (I changed this b/c I thought it would make the code easier to read moving forward) and dropping `addMainTheme()` (`theme_blank()` used in its place).

This PR has commits from #120 (commits 21ac7d1 - a0ce24d.)..I'll rebase once #120 is merged.

### CODE REVIEW

**Comment by daattali** [comment]
#120 is merged :)

**Comment by crew102** [comment]
this is ready to go

**Comment by daattali** [comment]
Thanks, I'll take a look hopefully on the weekend

**Comment by daattali** [comment]
OK not a hard PR to review -- but it's hard for me to wrap my head around the fact that theme_void() can be a dropin replacement for a whole custom function! I'll have to test

**Comment by daattali** [comment]
You're right, it does indeed work when I try modifying the theme, it still keeps it intact.

**Pull request merged**
