### PR TITLE
Test under ggplot2 v3.1.0

### PR DESCRIPTION
**Pull request by crew102**
This PR adds ggplot2 version 3.1.0 to the list of ggplot2 versions that ggExtra is tested under (partly in preparation for a PR for #90 which is on the way).

### CODE REVIEW

**Comment by daattali** [comment]
Travis is finally happy! Do you think this is ready to look at now?

**Comment by crew102** [comment]
so weird - nothing changed between 8d0c88d and dd303a1 that would have resulted in it going from fail -> pass, but I'll take it. Should be ready to look at.

**Comment by daattali** [comment]
Thanks for doing this, and trying to deal with the constant build fails!

The vector of package versions `c("2.2.0", "2.2.1", "3.0.0", "3.1.0", "latest")` seems to be reused in a few places and will be forgotten to be updated at some point in the future - can it be defined in one place?

**Comment by crew102** [comment]
Good call

**Comment by crew102** [comment]
No idea why this isn't passing. It passes for me locally (in docker container, that is). It appears to have something to do with the install of the dev version of ggplot2, though I don't see how that could be the case and have only 2 of the tests fail. Let's let this PR sit for a while and try later. I suspect this will resolve itself.

**Comment by daattali** [comment]
As the old saying goes, if at first you don't succeed... sit around and do nothing.

I wish there was a way to specify "pass if the two images are 99.99% identical" , like a fuzzy match.

**Comment by daattali** [comment]
Failing again..... is it always the ggplot2 dev version that fails?

**Comment by crew102** [comment]
I'm not sure...It seems totally random at this point when it will fail...It's gone from pass -> fail and back again several times with the only change in the code happening in the `after_script` phase of the Travi build (which shouldn't affect the build status). The last commit I made wasn't even a change per se - I just split a single commit into two separate commits b/c and it went from pass to fail. 

It seems to alternate between pass/fail for now apparent reason. I'm having trouble getting the detailed results of the test output as well (for some reason the ggExtra.Rcheck directory only exists if tests pass, not if they fail..again, no idea why).

**Comment by crew102** [comment]
I bet this next one passes:

**Comment by crew102** [comment]
Now it's failing but all tests are passing. 
asdfadf

**Comment by crew102** [comment]
K that last one failed b/c of a non-portable file name.

**Comment by crew102** [comment]
Looks like Travis hasn't been using the latest commit for the builds. For example, the last build used https://github.com/daattali/ggExtra/commit/2d174328c0cdd44e1880dbdd8f0462f67a16371e instead of https://github.com/daattali/ggExtra/pull/135/commits/57408cde29ae63a0c42eabcc6c12a50e86948f22.

**Pull request closed without merging**
