### PR TITLE
Fix subtitle position

### LINKED ISSUE #99: Subtitle position changes based on presence or absence of title
Hi,

I have a wrapper function around `ggExtra::ggMarginal()` in my package (it just adds results from statistical tests) and I noticed some unusual behavior with this function: It changes the position of the `subtitle` based on whether a `title` is present or not. Is this desired behavior? Is it possible to **always** have the `subtitle` on top of the marginal plots? Otherwise, at least in my view, the `subtitle` looks pretty cramped between the marginal distribution and the plot panel.

Here is a `reprex`:

``` r
# install.packages("devtools")
devtools::install_github("IndrajeetPatil/ggstatsplot")
#> Skipping install of 'ggstatsplot' from a github remote, the SHA1 (f801b442) has not changed since last install.
#>   Use `force = TRUE` to force installation

# without title
p1 <- ggstatsplot::ggscatterstats(data = iris,
                                  x = Sepal.Length,
                                  y = Sepal.Width)
#> Warning: This function doesn't return ggplot2 object. Thus, this plot is not further modifiable with ggplot2 commands.
#> 

# with title
p2 <- ggstatsplot::ggscatterstats(data = iris,
                                  x = Sepal.Length,
                                  y = Sepal.Width,
                                  title = "Dataset: Iris")
#> Warning: This function doesn't return ggplot2 object. Thus, this plot is not further modifiable with ggplot2 commands.
#> 

# plotting side-by-side to highlight the difference
cowplot::plot_grid(p1,
                   p2,
                   labels = c("(a)", "(b)"),
                   nrow = 1,
                   ncol = 2)
```

Created on 2018-03-11 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

### PR DESCRIPTION
**Pull request by crew102**
Pretty self-explanatory. Should close #99.

### CODE REVIEW

**Comment by daattali** [comment]
had to do some merges manually because of previous PR, but looks good. If it passes the travis checks, I'll merge to master and prepare for CRAN submission

**Comment by daattali** [comment]
Hmm it looks like that merge that I tried to do within the github web interface screwed something up, because tests are now failing. Were tests passing before for this PR? Do you mind submitting the PR again, I'm sorry for the extra trouble

**Comment by crew102** [comment]
Yep, I will rebase and resubmit later today

**Comment by crew102** [comment]
should be all set

**Pull request merged**
