### PR TITLE
Override colour/fill params when marginal mapping is chosen

### PR DESCRIPTION
**Pull request by crew102**

### CODE REVIEW

**Comment by daattali** [comment]
Actually, you think the check could be moved upstream, so that it only happens once (and therefore the message only appears once)?

**Comment by crew102** [comment]
Yeah I was thinking about the double messages myself. I think I favored doubling up b/c there may be a scenerio where the user specifies a col/fill in `xparams` or `yparams` and specifies a col/fill mapping in the marginal plots, in which case they would only get a single message, thus lending credence to the single/double message distinction. Plus it was easier for me to implement :)

I'll move the check to be higher in the stack sometime next week.

**Comment by crew102** [comment]
Hey Dean,

I moved the checks upstream in https://github.com/crew102/ggExtra/tree/move-param-check-upstream, as per your request. However, I think I would prefer that it not be used (i.e., I think we should leave it to one check per marginal). The reason is that there's no easy way to just specify one message when a parameter needs to get overrided from the `xparams` or `yparams` argument lists. For example, although this works nicely now (i.e., you only get one message):

```r
source("tests/testthat/helper-funs.R")
ggMarginal(margMapP(), groupColour = TRUE, colour = "red")
```

...This results in no messages:
```
ggMarginal(margMapP(), groupColour = TRUE, xparams = list(colour = "red"))
```

The implemention also results in more confusing code, in my opinion.

**Comment by daattali** [comment]
Sure let's leave as-is. Maybe when it becomes an R6 object it would make sense to add the warning message to the object itself and thus it'd be possible to not duplicate it (maybe, not a big deal)

**Pull request merged**
