### PR TITLE
Make sure marginal data comes from correct data frame

### PR DESCRIPTION
**Pull request by crew102**

### CODE REVIEW

**Comment by crew102** [comment]
I'll submit an updated PR for the marginal mapping feature once this is merged

**Comment by daattali** [comment]
Thanks for taking the initiative Chris! Have you checked what happens if there are multiple geom_point() layers? Would it take the first one (that would be fine, just make sure it doesn't error). Also, since this check is happening anyway, maybe it can be nice to throw an informative error if no appropriate layer is found, instead of whatever error R ends up throwing

**Comment by crew102** [comment]
It still works if there are multiple calls to `geom_point`...`getVarDF` just needs one of them to be happy. 

I've added an error message for when `getVarDF` can't find the data that it needs.

**Comment by daattali** [comment]
Awesome :)

**Pull request merged**
